[tool.poetry]
name = "airbnb-clone-backend-2"
version = "0.1.0"
description = ""
authors = ["wlarkspur"]
license = "MIT"
readme = "README.md"
packages = [{include = "airbnb_clone_backend_2"}]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
